### ISSUE TITLE
User links not working on the ovirt.org config page

### ISSUE THREAD

**Issue by david-caro** [oVirt/ovirt-site#23] opened 2015-12-15 15:40 UTC
The page: http://beta-ovirtweb.rhcloud.com/develop/infra/www.ovirt.org-configuration/

The links are at the end

**Comment by garrett** [comment] 2015-12-16 10:38
1. There was an early decision in the conversion process to remove user pages.
2. The page is extremely out of date anyway (as it is mainly about MediaWiki), so the content should be revised regardless.

**Comment by garrett** [comment] 2015-12-18 12:56
(Duplicate of #15, BTW.)

**Closed by garrett** 2015-12-18 12:56 UTC
