### ISSUE TITLE
Code owners configuration

### ISSUE THREAD

**Issue by MarSik** [oVirt/ovirt-site#1205] opened 2017-09-08 11:14 UTC
I recently noticed GitHub enabled a feature that allows specifying code owners for different pieces of code:

https://github.com/blog/2392-introducing-code-owners

It should supposedly automatically add the proper reviewers to patches.

Do you think it would make sense to enable it?

**Comment by mykaul** [comment] 2017-09-10 08:06
Sure - let's give it a try.
@JohnMarksRH - please see what needs to be done to enable it.

**Comment by sandrobonazzola** [comment] 2017-09-29 13:03
Closing duplicate of #1086

**Closed by sandrobonazzola** 2017-09-29 13:03 UTC
Labels: enhancement
