### ISSUE TITLE
oVirt Node ISO links broken

### ISSUE THREAD

**Issue by dougti** [oVirt/ovirt-site#788] opened 2017-02-10 19:38 UTC
Well, not broken exactly, but they all link to blank HTML pages. I see the ISOs are available in the parent directories however.

Page: http://www.ovirt.org/node/

Links:
- http://jenkins.ovirt.org/job/ovirt-node-ng_master_build-artifacts-el7-x86_64/lastSuccessfulBuild/artifact/exported-artifacts/latest-installation-iso.html
- http://jenkins.ovirt.org/job/ovirt-node-ng_master_build-artifacts-el7-x86_64/lastSuccessfulBuild/artifact/exported-artifacts/
- http://jenkins.ovirt.org/job/ovirt-node-ng_master_build-artifacts-el7-x86_64/lastSuccessfulBuild/artifact/exported-artifacts/ovirt-node-ng-installer-master-2017020204.iso

**Comment by sandrobonazzola** [comment] 2017-02-11 07:04
@yuvalturg can you please have a look?

**Comment by yuvalturg** [comment] 2017-02-12 12:24
It redirects to the iso in firefox, chrome is blocking this redirect with: "Refused to execute the redirect specified via '<meta http-equiv='refresh' content='...'>'. The document is sandboxed, and the 'allow-scripts' keyword is not set."

**Comment by sandrobonazzola** [comment] 2017-03-16 13:48
@yuvalturg is this still an issue or can we close it now?

**Comment by yuvalturg** [comment] 2017-03-16 14:10
it was fixed for chrome but yeasterday we saw it is not working at all with new version of firefox (recent f25 update), so we need to debug this again, lets keep it open

**Comment by duck-rh** [comment] 2017-03-17 09:46
wget says: Connecting to jenkins.ovirt.org (jenkins.ovirt.org)|66.187.230.92|:443... failed: No route to host.

So I guess this is not a browser issue but a network/infra one.

**Comment by duck-rh** [comment] 2017-03-17 09:52
This is due to this -> https://ovirt-jira.atlassian.net/browse/OVIRT-1243 (HTTPS connection to ovirt.org causes HSTS pinning for subdomains)

Unfortunately Jenkins is not HTTPS aware. For security and privacy reasons it really should anyway.

**Comment by jekader** [comment] 2017-03-17 10:46
I can't reproduce the problem - the links posted above do not return empty pages for me on Chrome 58.0.3029.19

@duck-rh I don't see how this is related to HSTS as neither the website link nor Jenkins has HTTPS in the initial ticket description. For me everything works via plain HTTP.

**Comment by duck-rh** [comment] 2017-03-19 03:26
HSTS was introduced in the apex configuration with the 'includeSubDomains' parameter (this was removed recently), so your browser would then automatically switch to HTTPS for all *.ovirt.org websites.

**Comment by sandrobonazzola** [comment] 2017-04-07 15:22
@duck-rh so can we close this? Is the link working now?

**Comment by duck-rh** [comment] 2017-04-10 05:49
yes

**Closed by duck-rh** 2017-04-10 05:49 UTC
