### ISSUE TITLE
Issue: /source/documentation/admin-guide/appe-oVirt_and_SSL.html.md

### ISSUE THREAD

**Issue by jflorian** [oVirt/ovirt-site#1995] opened 2019-05-19 21:02 UTC
### Description of the problem

Step 10 says `Edit the /etc/ovirt-imageio-proxy/ovirt-imageio-proxy.conf file:` but then gives shows the command `# vi /etc/ovirt-engine/ovirt-websocket-proxy.conf.d/10-setup.conf`, but the command should be `vi /etc/ovirt-imageio-proxy/ovirt-imageio-proxy.conf`.  In other words, the dialog references the correct file, but the example edit command references another file, which appears to be a copy/paste error from step 9.

**Comment by duck-rh** [comment] 2019-08-15 06:32
duplicate of #1989

**Closed by duck-rh** 2019-08-15 06:32 UTC
