### ISSUE TITLE
Wrong rendered list in the infra page

### ISSUE THREAD

**Issue by david-caro** [oVirt/ovirt-site#17] opened 2015-12-15 15:37 UTC
If you go to the 'Decision process' section in that infra page, there's a list that is not rendered properly.

The page is http://beta-ovirtweb.rhcloud.com/develop/infra/infrastructure/

**Comment by garrett** [comment] 2015-12-16 15:34
BTW: That's exactly how it is rendered on the wiki too. http://www.ovirt.org/Category:Infrastructure#Decision_process

The problem isn't rendering, but formatting in the source, both original wiki text and the problem was preserved in the Markdown conversion.

The fix is in pull request #27. :smiley:

**Closed** 2015-12-21 13:19 UTC
